version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      # 設定ファイル
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      # サイトデータ
      - ./data/site:/var/www/html
  db:
    build:
      context: .
      dockerfile: ./containers/mariadb/Dockerfile
    ports:
      # 空いてるポートとか
        - "3306:3306"
    volumes:
      - ./data/db/mariadb:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    volumes:
      # サイトデータ
      - ./data/site:/var/www/html
    depends_on:
      - db
